### PR TITLE
Cleanup errors in filter

### LINKED ISSUE #63: Cleanup errors in filters
Remove unnecessary semicolons:
- https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/filters/all.js#L148
- https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/filters/all.js#L339

Remove useless asignments, not used variables:
- https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/filters/all.js#L357
- https://github.com/asyncapi/java-spring-cloud-stream-template/blob/master/filters/all.js#L386
﻿

### PR DESCRIPTION
**Pull request by RageZBla**
**Description**

Remove some dead code and cleanup some syntx

**Related issue(s)**
Resolves #63

### CODE REVIEW

**Comment by derberg** [comment]
@RageZBla hey, sorry, I did not notice this PR before 😞 if you reopen, I'd love to merge it in as it is correct. I cannot reopen on my own

**Comment by RageZBla** [comment]
@derberg no problem. 🙇

**Comment by derberg** [comment]
@RageZBla oh sorry, just noticed PR is in the wrong place, should be opened here https://github.com/asyncapi/java-spring-cloud-stream-template/pulls

**Comment by RageZBla** [comment]
@derberg let me open the PR properly.

**Pull request closed without merging**
